name: TeamChat
version: ${project.version}
main: com.rathserver.teamchat.TeamChatPlugin
author: Nekoneko
website: https://www.nekonekoserver.net
description: Scoreboard TeamChat plugin.
api-version: 1.13
commands:
  teamchat:
    usage: /teamchat <on/off/exclusion>
    aliases: tc
    permission: teamchat.command
    description: TeamChat Toggle command.
  globalchat:
    aliases: g
    usage: /g <message>
    permission: teamchat.globalchat
    description: Global chat!
permissions:
  teamchat.command:
    default: op
  teamchat.globalchat:
    default: true
  teamchat.bypass:
    default: op
